version: "3.8"
services:
  frontend:
    # for manual build process
    # build:
      # context: ./videoflix_frontend
      # dockerfile: Dockerfile
    # for build with GitHub Actions
    image: ghcr.io/${IMAGE_OWNER}/videoflix-frontend:latest
    env_file: .env
    container_name: videoflix-frontend
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:80
    restart: on-failure
    networks:
      - videoflix-network

  backend:
    # for manual build process
    # build:
      # context: ./videoflix_backend
      # dockerfile: Dockerfile
    # for build with GitHub Action
    image: ghcr.io/${IMAGE_OWNER}/videoflix-backend:latest
    env_file: .env
    container_name: videoflix-backend
    ports:
      - ${BACKEND_EXTERNAL_PORT}:8000
    restart: on-failure
    depends_on:
      - db
      - redis
    networks:
      - videoflix-network

  db:
    image: postgres:13
    container_name: videoflix-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - videoflix-network
  
  redis:
    image: redis:7
    container_name: videoflix-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - videoflix-network

volumes:
  postgres_data:
    external: true
    name: videoflix-db-volume

networks:
  videoflix-network: